/**
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech) (7.3.0). https://openapi-generator.tech Do
 * not edit the class manually.
 */
package org.msp.quaoar.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import org.msp.quaoar.api.model.MemberDto;
import org.msp.quaoar.api.model.ResultDto;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
           date = "2024-11-28T15:28:22.418319539-05:00[America/Toronto]")
@Validated
@Controller
@Tag(name = "member", description = "the member API")
public interface MemberApi {

  default MemberApiDelegate getDelegate() {
    return new MemberApiDelegate() {};
  }

  /**
   * GET /member/{memberId}
   *
   * @param memberId id du membre (required)
   * @return OK (status code 200)
   *         or Not authorized (status code 400)
   */
  @Operation(operationId = "memberMemberIdGet",
             responses =
             {
               @ApiResponse(responseCode = "200", description = "OK",
                            content =
                            {
                              @Content(mediaType = "application/json",
                                       schema = @Schema(implementation =
                                                            MemberDto.class))
                            })
               ,
                   @ApiResponse(
                       responseCode = "400", description = "Not authorized",
                       content = {
                         @Content(mediaType = "application/json",
                                  schema =
                                      @Schema(implementation = ResultDto.class))
                       })
             },
             security = { @SecurityRequirement(name = "ApiKeyAuth") })
  @RequestMapping(method = RequestMethod.GET, value = "/member/{memberId}",
                  produces = {"application/json"})

  default ResponseEntity<MemberDto>
  memberMemberIdGet(@Parameter(name = "memberId", description = "id du membre",
                               required = true, in = ParameterIn.PATH)
                    @PathVariable("memberId") Integer memberId) {
    return getDelegate().memberMemberIdGet(memberId);
  }

  /**
   * POST /member/{memberId}/save
   *
   * @param memberId Id du memmbre (required)
   * @param memberDto  (required)
   * @return OK (status code 200)
   */
  @Operation(operationId = "memberMemberIdSavePost",
             responses =
             {
               @ApiResponse(
                   responseCode = "200", description = "OK", content = {
                     @Content(mediaType = "application/json",
                              schema =
                                  @Schema(implementation = MemberDto.class))
                   })
             },
             security = { @SecurityRequirement(name = "ApiKeyAuth") })
  @RequestMapping(method = RequestMethod.POST,
                  value = "/member/{memberId}/save",
                  produces = {"application/json"},
                  consumes = {"application/json"})

  default ResponseEntity<MemberDto>
  memberMemberIdSavePost(@Parameter(name = "memberId",
                                    description = "Id du memmbre",
                                    required = true, in = ParameterIn.PATH)
                         @PathVariable("memberId") Integer memberId,
                         @Parameter(name = "MemberDto", description = "",
                                    required = true) @Valid
                         @RequestBody MemberDto memberDto) {
    return getDelegate().memberMemberIdSavePost(memberId, memberDto);
  }
}
