openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: https://localhost:8080/v1
paths:
  /sanity:
    get:
      summary: check si le service est up
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SanityDto'
components:
  schemas:
    SanityDto:
      type: object
      properties:
        status:
          type: integer
          format: int64
          example: 1
        msg:
          type: string
          example: ça va bien